In [1]:
import numpy as np
my_arr = np.arange(21)
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
my_arr[10]

10

In [3]:
my_arr[5:15]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
my_arr[5:15:5]

array([ 5, 10])

In [5]:
two_dim = np.array([[0,10,20],[5,15,25],[100,200,300]])
two_dim

array([[  0,  10,  20],
       [  5,  15,  25],
       [100, 200, 300]])

In [6]:
# wyciagi info z 1 wiersza indexing od 0 
two_dim[0]

array([ 0, 10, 20])

In [7]:
two_dim[1]

array([ 5, 15, 25])

In [8]:
# [najpierw wiersz] [potem kolumna]
two_dim[1][0]

5

In [9]:
#skrócenie wymiaru 
two_dim[1:3,:2]

array([[  5,  15],
       [100, 200]])

In [10]:
two_dim[1:3]

array([[  5,  15,  25],
       [100, 200, 300]])

In [11]:
#fancy indexing

In [12]:
my_arr = np.arange(25).reshape(5,5)
my_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
my_arr[(0,1)]

1

In [14]:
my_arr[(0,1),]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
my_arr[[0,1],[0,4]]

array([0, 9])

In [16]:
vals = np.array([100,5,0])
select = np.random.randint(0,3,size=(4,3))
select

array([[0, 2, 2],
       [0, 2, 0],
       [2, 1, 2],
       [1, 1, 0]])

In [17]:
vals[select]

array([[100,   0,   0],
       [100,   0, 100],
       [  0,   5,   0],
       [  5,   5, 100]])

In [18]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
slice_of_arr = arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [20]:
slice_of_arr[:] = 100
slice_of_arr

array([100, 100, 100, 100, 100])

In [21]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [22]:
fancy_arr = np.arange(10)
fancy_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
fancy_index_arr = fancy_arr[np.arange(5)]
fancy_index_arr

array([0, 1, 2, 3, 4])

In [24]:
fancy_index_arr[:] = 100
fancy_index_arr

array([100, 100, 100, 100, 100])

In [25]:
fancy_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
slice_of_arr.base is None

False

In [27]:
fancy_index_arr.base is None

True

In [28]:
slice_of_arr.base is arr

True

In [29]:
arr = np.arange(10)
print('arr')
print(arr)

slice_of_arr = arr[:5].copy()
print('slice_of_arr')
print(slice_of_arr)

slice_of_arr[:] = 100
print('slice_of_arr')
print(slice_of_arr)

print('arr')
print(arr)

arr
[0 1 2 3 4 5 6 7 8 9]
slice_of_arr
[0 1 2 3 4]
slice_of_arr
[100 100 100 100 100]
arr
[0 1 2 3 4 5 6 7 8 9]


In [30]:
slice_of_arr is arr

False

In [31]:
# Znajdź indeksy niezerowych elementów z tablicy array([1,2,0,0,4,0])

In [32]:
arr = ([1, 2, 0, 0, 4, 0])
index_no = []
for i in range(len(arr)):
    if arr[i] != 0:
        index_no.append(i)
print(index_no)

[0, 1, 4]


In [33]:
arr = np.arange(0,50,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [34]:
arr>15

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
arr[arr>15]

array([20, 25, 30, 35, 40, 45])

In [36]:
(arr>15) & (arr!=40)

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

In [37]:
arr[(arr>15) & (arr!=40)]

array([20, 25, 30, 35, 45])

In [38]:
(arr<10) | (arr>=20)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [39]:
arr[(arr<10) | (arr>=20)]

array([ 0,  5, 20, 25, 30, 35, 40, 45])

In [40]:
np.logical_or(arr<10,arr>=20)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [41]:
arr[np.logical_or(arr<10,arr>=20)]

array([ 0,  5, 20, 25, 30, 35, 40, 45])

In [42]:
np.where(arr<=43)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)

In [43]:
#Ćwiczenia
#Wyfiltruj z arr tylko te wartości, które są mniejsze od 10 lub większe bądź równe 20, 
#ale jednocześnie różne od liczby 40. (gdzie arr = np.arange(0,50,5)).


In [44]:
arr = np.arange(0,50,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [45]:
np.logical_or(arr<10,arr>=20)& (arr!=40)

array([ True,  True, False, False,  True,  True,  True,  True, False,
        True])

In [46]:
arr[np.logical_or(arr<10,arr>=20)& (arr!=40)]

array([ 0,  5, 20, 25, 30, 35, 45])

In [47]:

#Wykorzystując operator XOR, stwórz macierz o kształcie (4,4), 
# której elementy po głównej przekątnej mają wartość logiczną False, a pozostałe wartość True.

In [48]:
arr = np.arange(16).reshape(4, 4)

In [49]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
(arr != 0) & (arr != 5) & (arr != 10) & (arr != 15)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [51]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
np.logical_xor(1, np.eye(4))

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [53]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [54]:
arr[[3,0,1],:3]

array([[15, 16, 17],
       [ 0,  1,  2],
       [ 5,  6,  7]])

In [55]:
arr.sum()

190

In [56]:
arr[arr.sum(axis=1)>10,2:]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [57]:
arr[arr.sum(axis=1)>10,2:]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [58]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
#Ćwiczenie
# Zwróć z tablicy arr wiersz o indeksie nr 2, lecz tylko dla tych kolumn, których suma przekracza 30.

In [60]:
arr[2][arr.sum(axis=0)>30]

array([11, 12, 13, 14])

In [61]:
#Mamy dane dwie tablice: a i b. Stwórz program filtrujący wartości z b, które korespondują z elementami a i są większe od 100 i mniejsze od 110.

# a = np.array([97,101,105,111,117,125])
# b = np.array(['a','e','i','o','u','y'])

In [62]:
a = np.array([97,101,105,111,117,125])
b = np.array(['a','e','i','o','u','y'])

In [63]:
dict = {}
aa = np.array([])
bb = np.array([])
for index in range(0, len(a)):
    if 100 < a[index] < 110:
        dict[b[index]] = a[index]
        aa = np.append(aa, [a[index]])
        bb = np.append(bb, [b[index]])

print(dict)
print(aa)
print(bb)


{'e': 101, 'i': 105}
[101. 105.]
['e' 'i']


In [ ]:
#Stwórz program, który ze wskazanej macierzy wyciągnie odpowiednio najmniejszą
# i największą wartość dla każdego wiersza.

In [71]:
m = np.array([[0,4,1],
              [2,0,4]])

In [70]:
m.max(axis=1)

array([4, 4])

In [72]:
m.min(axis=1)

array([0, 0])

In [73]:
# Mając tablicę np.arange(11), odwróć znak wszystkich elementów większych od 3 i mniejszych od 8.

In [79]:
ars= np.arange(11)
ars

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
ac = np.array([])
for liczba in range(0, len(ars)):
    if 3 < ars[liczba] < 8:
        ac = np.append(ac, [ars[liczba] * -1])

print(ac)

[-4. -5. -6. -7.]
