In [1]:
#Broadcasting

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,101,10)
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [4]:
arr + arr

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200])

In [5]:
arr * arr

array([    0,   100,   400,   900,  1600,  2500,  3600,  4900,  6400,
        8100, 10000])

In [6]:
arr + 5

array([  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105])

In [7]:
arr / 5

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [8]:
left_ = np.arange(10).reshape(5,2)
right_ = np.arange(5).reshape(5,1)

left_

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
right_

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [10]:
left_ * right_

array([[ 0,  0],
       [ 2,  3],
       [ 8, 10],
       [18, 21],
       [32, 36]])

In [11]:
# Funkcje uniwersalne

In [12]:
arr = np.arange(0,101,10)
arr


array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [13]:
#pierwiastek kwadratowy
np.sqrt(arr)

array([ 0.        ,  3.16227766,  4.47213595,  5.47722558,  6.32455532,
        7.07106781,  7.74596669,  8.36660027,  8.94427191,  9.48683298,
       10.        ])

In [14]:
# sinus ;) ?
np.sin(arr) 

array([ 0.        , -0.54402111,  0.91294525, -0.98803162,  0.74511316,
       -0.26237485, -0.30481062,  0.77389068, -0.99388865,  0.89399666,
       -0.50636564])

In [15]:
np.multiply(arr,2)

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200])

In [16]:
#Ćwiczenia
# 1. Stwórz program, który ze wskazanej macierzy wyciągnie odpowiednio najmniejszą i największą wartość dla każdego wiersza.
# [[0 4 1] [2 0 4]]

# 2. Stwórz wektor Z według następującego wzoru: np.random.uniform(0,1,10). 
# Następnie znajdź element, który jest najbliższy wartości 0.5.
# 3. Stwórz wektor zawierający 20 losowych wartości, a następnie zamień jego największą wartość na 0.

# 4. Znajdź części całkowite tablicy, wykorzystując przynajmniej dwa różne sposoby.
# np.array([5, 0.0249139 , 0.11873564, 0., 0.72321586, 11308494, 0.29931472, 0.24439968, 0.61251754, 4])

In [17]:
# ad. 1
m = np.array([[0,4,1],
              [2,0,4]])

In [18]:
m.min(axis=1)

array([0, 0])

In [19]:
m.max(axis=1)

array([4, 4])

In [20]:
# ad. 2
x =np.random.uniform(0,1,10)

In [21]:
x

array([0.39406416, 0.94525189, 0.02334823, 0.49213623, 0.27505761,
       0.64368203, 0.80820998, 0.05316542, 0.19246594, 0.19960368])

In [22]:
x[np.abs(np.array(x) - 0.5).argmin()]

0.49213622661476697

In [23]:
# ad. 3
y =np.random.uniform(0,66,20)

In [24]:
y

array([49.77495417, 45.56232801, 60.74882394, 45.17521922, 52.34033757,
       43.35429966, 11.79306131, 51.15435742, 65.86213609,  0.2581034 ,
       28.33053162, 37.84766351, 10.01618771, 44.27656443, 24.24672866,
       48.53929125, 46.73815232, 47.73999712, 32.3254039 ,  5.74601061])

In [25]:
np.amax(y)

65.86213608782937

In [26]:
y[y.argmax()] = 0
y

array([49.77495417, 45.56232801, 60.74882394, 45.17521922, 52.34033757,
       43.35429966, 11.79306131, 51.15435742,  0.        ,  0.2581034 ,
       28.33053162, 37.84766351, 10.01618771, 44.27656443, 24.24672866,
       48.53929125, 46.73815232, 47.73999712, 32.3254039 ,  5.74601061])

In [27]:
# ad4.
q= np.array ([5, 0.0249139 , 0.11873564, 0., 0.72321586, 11308494, 0.29931472, 0.24439968, 0.61251754, 4])

In [28]:
q

array([5.0000000e+00, 2.4913900e-02, 1.1873564e-01, 0.0000000e+00,
       7.2321586e-01, 1.1308494e+07, 2.9931472e-01, 2.4439968e-01,
       6.1251754e-01, 4.0000000e+00])

In [29]:
f =np.equal(np.mod(q, 1), 0)
# 1 sposób

In [30]:
f

array([ True, False, False,  True, False,  True, False, False, False,
        True])

In [31]:
np.mod(q, 1, out=q)
mask = (q == 0)
# 2 sposób

In [32]:
mask

array([ True, False, False,  True, False,  True, False, False, False,
        True])

In [33]:
#Agregowanie

In [34]:
arr.sum()

550

In [35]:
arr.mean()

50.0

In [36]:
arr.min()

0

In [37]:
arr.max()

100

In [38]:
arr = np.arange(0,101,10)
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [39]:
arr / arr

C:\Users\may\AppData\Local\Temp/ipykernel_17796/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [40]:
defaults = np.seterr(all='ignore')

In [41]:
arr / arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [42]:
_ = np.seterr(**defaults)

In [43]:
arr / arr

C:\Users\may\AppData\Local\Temp/ipykernel_17796/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [44]:
arr = np.random.randint(1,40,10)
arr

array([30, 25, 35, 12, 18,  9, 21, 17, 27, 21])

In [45]:
np.sort(arr)

array([ 9, 12, 17, 18, 21, 21, 25, 27, 30, 35])

In [46]:
arr2d = np.array([np.arange(1,6),np.arange(6,1,-1)]).reshape(5,2)
arr2d

array([[1, 2],
       [3, 4],
       [5, 6],
       [5, 4],
       [3, 2]])

In [47]:
np.sort(arr2d)

array([[1, 2],
       [3, 4],
       [5, 6],
       [4, 5],
       [2, 3]])

In [48]:
np.sort(arr2d,axis=0)

array([[1, 2],
       [3, 2],
       [3, 4],
       [5, 4],
       [5, 6]])

In [65]:
dt = np.dtype([('student','S10'),('exam1',int),('exam2',int)])

a = np.array([("Student A",89,74),("Student B",85,56),
              ("Student C", 93,44), ("Student D",83,92)],dtype=dt)

a

array([(b'Student A', 89, 74), (b'Student B', 85, 56),
       (b'Student C', 93, 44), (b'Student D', 83, 92)],
      dtype=[('student', 'S10'), ('exam1', '<i4'), ('exam2', '<i4')])

In [68]:
np.sort(a,order='exam2')

array([(b'Student C', 93, 44), (b'Student B', 85, 56),
       (b'Student A', 89, 74), (b'Student D', 83, 92)],
      dtype=[('student', 'S10'), ('exam1', '<i4'), ('exam2', '<i4')])

In [69]:
np.sort(a,order='exam2')[-1][0]

b'Student D'

In [70]:
arr

array([30, 25, 35, 12, 18,  9, 21, 17, 27, 21])

In [71]:
np.argsort(arr)

array([5, 3, 7, 4, 6, 9, 1, 8, 0, 2], dtype=int64)

In [72]:
#Ćwiczenie

#Posortuj wektor arr w sposób malejący, biorąc pod uwagę wyniki z drugiego egzaminu.

In [93]:
x =np.sort(a,order='exam2')

In [94]:
x

array([(b'Student C', 93, 44), (b'Student B', 85, 56),
       (b'Student A', 89, 74), (b'Student D', 83, 92)],
      dtype=[('student', 'S10'), ('exam1', '<i4'), ('exam2', '<i4')])

In [85]:
x =np.sort(a,order='exam2')

In [97]:
y = np.sort(a,order='exam2')
z = list(reversed(y))

In [92]:
z

[(b'Student D', 83, 92),
 (b'Student A', 89, 74),
 (b'Student B', 85, 56),
 (b'Student C', 93, 44)]

In [98]:
d =np.sort(a,order='exam2')[::-1]

In [99]:
d

array([(b'Student D', 83, 92), (b'Student A', 89, 74),
       (b'Student B', 85, 56), (b'Student C', 93, 44)],
      dtype=[('student', 'S10'), ('exam1', '<i4'), ('exam2', '<i4')])