In [2]:
import numpy as np

In [3]:
exams = np.asarray([[100, 200, 50, 400], [50, 0, 0, 100], [350, 100, 50, 200]])

In [4]:
exams

array([[100, 200,  50, 400],
       [ 50,   0,   0, 100],
       [350, 100,  50, 200]])

In [5]:
u_a = [100,200,50,400]
u_b = [50,0,0,100]
u_c = [350,100,50,200]
exams = [u_a,u_b,u_c]

In [6]:
exams

[[100, 200, 50, 400], [50, 0, 0, 100], [350, 100, 50, 200]]

In [7]:
#Speed test

In [8]:
my_list = [i for i in range(1000000)]
my_array = np.arange(1000000)

In [9]:
%time for _ in range(10): my_list2 = [x**2 for x in my_list]

Wall time: 3.32 s


In [10]:
%time for _ in range(10):my_array_2 = my_array **2

Wall time: 33 ms


In [11]:
one_dim = np.array([1,2,3,4])
type(one_dim)

numpy.ndarray

In [12]:
one_dim.shape # kształt

(4,)

In [13]:
one_dim.ndim # liczba wymiarów – w tym przypadku 1 wymiar

1

In [14]:
two_dim = np.array([[100, 200, 50, 400], [50, 0, 0, 100], [350, 100, 50, 200]])

print("len: " + str(len(two_dim)))
print("shape: " + str(two_dim.shape))
print("ndim: " + str(two_dim.ndim))

len: 3
shape: (3, 4)
ndim: 2


In [15]:
one_dim

array([1, 2, 3, 4])

In [16]:
one_dim.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [17]:
two_dim

array([[100, 200,  50, 400],
       [ 50,   0,   0, 100],
       [350, 100,  50, 200]])

In [18]:
two_dim.reshape(4,3)

array([[100, 200,  50],
       [400,  50,   0],
       [  0, 100, 350],
       [100,  50, 200]])

In [19]:
two_dim.reshape(4,4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [21]:
two_dim.transpose()

array([[100,  50, 350],
       [200,   0, 100],
       [ 50,   0,  50],
       [400, 100, 200]])

In [22]:
my_list = [1,2,3,4,5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [23]:
my_nested_list = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_nested_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.ones((2,3),dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [31]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [57]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.random.rand(5)

array([0.97331398, 0.33459613, 0.24974297, 0.49314121, 0.16102346])

In [33]:
np.random.rand(5,5)

array([[0.49434419, 0.0146706 , 0.52350675, 0.94803859, 0.86225721],
       [0.40595749, 0.94782566, 0.28849402, 0.14783281, 0.2481257 ],
       [0.44211986, 0.48198183, 0.45453583, 0.29277472, 0.08256705],
       [0.57281321, 0.84981557, 0.11588104, 0.25479608, 0.19029118],
       [0.3238004 , 0.52571315, 0.87865407, 0.42258074, 0.77192021]])

In [34]:
np.random.randint(1,100,10)

array([37, 96, 47, 68, 95, 95, 86, 46, 55, 20])

In [35]:
#Stwórz dziesięcioelementowy wektor z przedziału od 0 do 1, bez uwzględniania wartości granicznych.
np.random.randint(1,10,10)

array([3, 7, 6, 2, 9, 2, 1, 7, 2, 6])

In [55]:
#Stwórz macierz o wymiarach 5x5, której wartości w poszczególnych wierszach są równe, 
#a wartości w kolumnach wynoszą 0, 1, 2, 3, 4
x,y =np.mgrid[0:5,0:5]

In [56]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])